name=input("Hello, what is your name?: ")
print("Hello", name, ", my name is python unit two project")
print("")
origin=input("Where are you from?: ")
if origin in ("maryland", "Maryland", "DC", "Washington DC"):
    print("Oh, I really hate people from there,")
else:print("O that's cool")
print("")
fav_num=input("What is your favorite number?: ")
hehe=((float(fav_num)+1.1)*5.34785237777)
print("Well my favorite number is", hehe,"," "That is the serial number of my dyson electric toothbrush!")
print("")
fav_car=input("What is your favorite car?: ")
print("Wow, very cool. I think that a",fav_car,"is an interesting choice.")
print("")
car_cost=input("How much money does your favorite car cost?: ")
car_interest=input("And what is the monthly interest rate on that car?(Enter a value such as 1.5 or 2.6): ")
payment_time=input("And finally, how many months will your car loan be for?: ")
total_cost=(float(car_interest)*int(car_cost)/1-(1+float(car_interest))**-int(payment_time))
print("$",(total_cost), "is the total cost of your car, interest included.")